name: Development

on:
  push:
    branches:
      - development

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25.7.0
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm -w packages/rollup-plugin-sitemap run lint

      - name: Build
        run: npm -w packages/rollup-plugin-sitemap run build
