name: Production

on:
  push:
    branches:
      - production

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25.7.0
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm -w packages/rollup-plugin-sitemap run lint

      - name: Run tests with coverage
        run: npm -w packages/rollup-plugin-sitemap test

      - name: Build
        run: npm -w packages/rollup-plugin-sitemap run build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./packages/rollup-plugin-sitemap/coverage
          token: ${{ secrets.CODECOV_TOKEN }}
